### PR TITLE
Add option for hiding errors

### PR DESCRIPTION
**Pull request by abelmokadem**

### CODE REVIEW

**Comment by scottcorgan** [comment]
Cool. What's your use case for this?

**Comment by abelmokadem** [comment]
I'm using tape inside a cli command for validating OpenAPI files that contain certain `x-` extensions. The users of the cli tool are not interested in stack traces, but in the actual messages.

**Comment by abelmokadem** [comment]
I have released this under my own scope for now. You can close this PR or merge it if you still want it.

**Comment by scottcorgan** [comment]
If you can update the docs, I'd be happy to merge this!

**Pull request closed without merging**
